### ISSUE TITLE
allow unknown teaching and exercise time

### ISSUE THREAD

**Issue by zkamvar** [carpentries/sandpaper#395]
When people are developing lessons, they often do not know time estimates, some will leave the fields blank and others will insert non-numeric characters into the fields:

```yaml
title: Introduction to RNA-seq
teaching: XX
exercises: XX
```

We should allow these as this is a natural part of the development process.

 - [x] allow non-numeric entries to `teaching` and `exercises` YAML items
 - [x] set a default time of 5 minutes for each
 - [x] throw message or warning about the episodes with missing times
