### ISSUE TITLE
Allow relative paths in navigation in config.yaml or allow transparently using symlinks

### ISSUE THREAD

**Issue by apirogov** [carpentries/sandpaper#504]
Currently the only way to have the same page appear in both learners and instructors view appears to be duplicating the content.

A clean solution would be either to allow something like:

```yaml
learners: 
- acknowledgements.Rmd

instructors: 
- ../learners/acknowledgements.Rmd
```

or allowing to use a symlink in place of the file.

In both cases currently the validation fails complaining that the file does not exist.
